apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-mvc-example-deployment
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: spring-mvc-example
  template:
    metadata:
      labels:
        app: spring-mvc-example
    spec:
      containers:
        - name: spring-mvc-example-container
          image: omkdesai.jfrog.io/gs-serving-web-docke-docker/test:main-51
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred
