name: Deploy Workflow

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag to deploy'
        required: true

env:
  DOCKER_REGISTRY: "omkdesai.jfrog.io"
  IMAGE_NAME: "omkdesai.jfrog.io/gs-serving-web-docke-docker/test"

jobs:
  deploy_to_gke:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Get GKE Cluster Credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: 'autopilot-cluster-1'
        location: 'us-central1'
        credentials: ${{ secrets.GCP_SA_KEY }}

    - name: Apply Kubernetes Manifest
      run: |
        kubectl apply -f ../.kube/manifest.yaml
