name: Deploy Workflow
# on:
#   workflow_dispatch:
#     inputs:
#       deploy-environment:
#         type: choice
#         description: 'Deploy Environment'
#         options:
#         - main
#         - dev
#         - qa
#         - prod
#         required: true
#         default: 'dev'
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag to deploy'
        required: true

env:
  # TODO: Change to name of your Docker Registry (eg. jfrog.io)
  DOCKER_REGISTRY: "omkdesai.jfrog.io"
  # TODO: Change part to name of your Docker Registry (eg. omkdesai.jfrog.io/jf repo name/image-name)
  IMAGE_NAME: "omkdesai.jfrog.io/gs-serving-web-docke-docker/test"
  image: "${{github.event.inputs.image_tag}}"
jobs:

  deploy_to_gke:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - uses: google-github-actions/setup-gcloud@1bee7de035d65ec5da40a31f8589e240eba8fde5
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    - uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
      with:
        cluster_name: 'autopilot-cluster-1'
        location: 'us-central1'
        credentials: ${{ secrets.GCP_SA_KEY }}      

    - name: Apply Kubernetes Manifest
        run: |
          kubectl apply -f ../.kube/manifest.yaml
